version: "3.9"
services:
  web:
    depends_on:
      - nivlheimapi
    image: nivlheimwww
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - data:/var/www/nivlheim
      - logs:/var/log
    networks:
      - backend

  nivlheimapi:
    depends_on:
      postgres:
        condition: service_healthy
    image: nivlheim
    restart: always
    volumes:
      - data:/var/www/nivlheim
      - logs:/var/log
    networks:
      - backend
    environment:
      - NIVLHEIM_PGHOST=postgres
      - NIVLHEIM_PGUSER=nivlheim
      - NIVLHEIM_PGPASSWORD=notsecret
      - NIVLHEIM_PGDATABASE=nivlheim
      - NIVLHEIM_PGSSLMODE=disable
      - NIVLHEIM_HTTPLISTENADDRESS=:4040

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=nivlheim
      - POSTGRES_DB=nivlheim
      - POSTGRES_PASSWORD=notsecret
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "--username=nivlheim"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 3s

networks:
  backend:

volumes:
  data:
  logs:
